# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np # import numpy library in jupyter notebook
arr2d = np.arange(0,10).reshape(2,5) # take elements from 0 to 9 and made it 2dim
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [21]:
# let us take arr2d from Question:1 above
arr2d
# making another 2x5 with ones() to stack vertically
arr_2nd = np.ones((2,5), dtype = np.int32) # casted to int32 to remove decimals
arr_2nd
v_stacked_arr = np.vstack((arr2d, arr_2nd))
v_stacked_arr # hence the required output

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [23]:
# lets take two arrays from Question:2 to get desired output
arr2d, arr_2nd
# horizontal stacking as
h_stack = np.hstack((arr2d, arr_2nd))
h_stack # hence the output

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [27]:
# let assume a 2d array from Question:1 above
arr2d
# making it flat
arr2d.flatten() # hence the output is exactly the same as desired output above

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [53]:
# lets create 2D aray
array_2d = np.arange(0,15).reshape(3,5)
array_2d
# lets convert it into 1D
array_2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [11]:
# let us convert one dim to 2 dim
# let us create one dim array first
arr1d = np.arange(0,15)
arr1d
# conversion to 2d 
arr2d = arr1d.reshape(5,3)
arr2d # check dimensions with arr2d.ndim or np.ndim(arr2d)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [17]:
# creating 5 by 5 array
five_five_arr = np.arange(25).reshape(5,5)
five_five_arr
# getting square of five_five_arr
sq = (five_five_arr)**2
sq

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [42]:
# creating 5x6 array
five_six_arr = np.arange(30).reshape(5,6)
print(five_six_arr)
# finding mean with.mean()
print(f"\nMean:\n{five_six_arr.mean()}")

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

Mean:
14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [40]:
# let us take five_six_arr array and find standard deviation
print(f"Standard Deviation:\n{five_six_arr.std()}")

Standard Deviation:
8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [39]:
# let us take five_six_arr array and find standard deviation
median = np.median(five_six_arr)
print(f"Median:\n{median}")

Median:
14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [29]:
# transpose
five_six_arr.T # or np.transpose(five_six_arr)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [44]:
four_four_arr = np.arange(16).reshape(4,4)
print(f"4x4 array:\n{four_four_arr}\n")
# finding diagonal
diagonal_elements = np.diagonal(four_four_arr)
print(f"diagonal elements:\n{diagonal_elements}")
# sum of diagonal elements
sum_up = diagonal_elements.sum()
print("\nSum:\n",sum_up)

4x4 array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

diagonal elements:
[ 0  5 10 15]

Sum:
 30


## Question:13

### Find the determinant of the previous array in Q12?

In [62]:
# finding determinant using array from Question 12 
from numpy.linalg import det # determinant det() import from linalg module
determinant = np.linalg.det(four_four_arr)
print(f"Determinant:\n{determinant}")

Determinant:
0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [3]:
# suppose an array 
array = np.array([1,2,3,4,5,6,7,8,9,10])
# for 5th percentile 
x = np.percentile(array,5)
print(f"The 5th percentile:{x}")
# for 95th percentile 
y = np.percentile(array,95)
print(f"The 95th percentile:{y}")

The 5th percentile:1.4500000000000002
The 95th percentile:9.549999999999999


## Question:15

### How to find if a given array has any null values?

In [14]:
# suppose an array as 
arr = np.array([1,2,3,4,5,6,7,np.NaN])
x = np.argwhere(np.isnan(arr))
print("Null value at Index:",x)

Null value at Index: [[7]]
